# Generated by Django 3.0.7 on 2020-06-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='rooms',
            new_name='room',
        ),
    ]
